# Generated by Django 3.1.7 on 2021-03-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffaccounts',
            old_name='total_amount',
            new_name='total_amount_staff',
        ),
        migrations.RenameField(
            model_name='studentaccounts',
            old_name='total_amount',
            new_name='total_amount_student',
        ),
    ]
